name: learn-github-actions
# on: [push]
on: workflow_dispatch
jobs:
   job1:
    runs-on: ubuntu-latest
    steps:
    - run: |
        pwd 
        ifconfig 
        echo "${{ env.RUNNER_OS }}" 
        if: env.RUNNER_OS = 'test-varible-labels'
        echo "哈哈"
   


   jobs2:
    runs-on: windows-latest
    steps:
    - run: node --version
env:
   RUNNER_OS: ${{ vars.RUNNER_OS }}