name: learn-github-actions
on: [push]
jobs:
   job1:
    runs-on: ubuntu-latest
    steps:
    - run: pwd 
    - run: ifconfig 

   jobs2:
    runs-on: windows-latest
    steps:
    - run: node --version
