name: learn-github-actions
on: [push]
jobs:
   job1:
    runs-on: ubuntu-latest
    steps:
    - run: pwd 
    - run: ifconfig 
    - run: echo "${{ env.RUNNER_OS }}"


   jobs2:
    runs-on: windows-latest
    steps:
    - run: node --version
env:
   RUNNER_OS: ${{ vars.RUNNER_OS }}